services:

    stable_diffusion_discord_bot:
        build:
            context: ./
            dockerfile: docker/stable-diffusion-bot/Dockerfile
        container_name: stable_diffusion_discord_bot
        env_file:
            - ./docker/stable-diffusion-bot/.env
        image: stable_diffusion_discord_bot
        volumes:
            - ./code/stable-diffusion-bot:/code

    animagine_discord_bot:
        build:
            context: ./
            dockerfile: docker/animagine-bot/Dockerfile
        container_name: animagine_discord_bot
        env_file:
            - ./docker/animagine-bot/.env
        image: animagine_discord_bot
        volumes:
            - ./code/animagine-bot:/code

    ollama_server:
        build:
            context: ./
            dockerfile: docker/ollama-server/Dockerfile
        container_name: ollama_server
        image: ollama_server
        volumes:
            - ./code/ollama-server:/code

    ollama_discord_bot:
        build:
            context: ./
            dockerfile: docker/ollama-bot/Dockerfile
        container_name: ollama_discord_bot
        env_file:
            - ./docker/ollama-bot/.env
        image: ollama_discord_bot
        volumes:
            - ./code/ollama-bot:/code
